# Generated by Django 5.0 on 2024-01-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='shop/media/uploads/products/GettyImages-912168376-fb70bef6e7db4af59a02f5b0f69b9366_eAeD77X.webp', upload_to='uploads/blog/posts/'),
        ),
    ]
