# Generated by Django 5.0 on 2024-01-21 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='visit',
        ),
        migrations.AddField(
            model_name='post',
            name='visit',
            field=models.ManyToManyField(related_name='post_visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
