# Generated by Django 5.0 on 2024-01-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_visit_post_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='visit',
        ),
        migrations.AddField(
            model_name='post',
            name='visit',
            field=models.IntegerField(default=0),
        ),
    ]
